project:
  type: website

website:
  title: "Pseudo State"
  navbar:
    left:
      - href: get_started.qmd
        text: Get Started
      - file: reference/index.qmd
        text: "Reference"

metadata-files:
  - _sidebar.yml


quartodoc:
  sidebar: "_sidebar.yml"
  package: pseudostate
  sections:
    - title: Getting Started
      desc: Introduction to the package.