project:
  type: website

website:
  title: "Pseudo State"
  navbar:
    left:
      - href: get_started.qmd
        text: Get Started
      - file: reference/index.qmd
        text: "Reference"

metadata-files:
  - _brand.yml
  - _sidebar.yml


quartodoc:
  sidebar: "_sidebar.yml"
  package: pseudostate
  sections:
    - title: API Reference
      desc: Core functions for computing pseudo-state estimates.
      contents:
        - calculate_pseudostates